#
# name="$(basename $(pwd))"
# cd ./src/
# echo "Building dist/${name} for linux/amd64..."
# env GOOS=linux GOARCH=amd64 go build -o ../dist/${name}-linux-amd64 .
# echo "Building dist/${name} for linux/arm64..."
# env GOOS=linux GOARCH=arm64 go build -o ../dist/${name}-linux-arm64 .
# echo "Building dist/${name} for darwin/amd64..."
# env GOOS=darwin GOARCH=amd64 go build -o ../dist/${name}-darwin-amd64 .
# echo "Building dist/${name} for darwin/arm64..."
# env GOOS=darwin GOARCH=arm64 go build -o ../dist/${name}-darwin-arm64 .
# cd ../