name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test_go:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Tests
        shell: /usr/bin/env bash -e {0}
        working-directory: src/
        run: go test ./...
